version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: root
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask_api:
    build: ./app
    container_name: flask_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_USER: root
      MONGO_PASS: secret
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: root
    depends_on:
      - mongo

  prometheus-flask-api:
    image: prom/prometheus:latest
    container_name: prometheus-flask-api
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - flask_api
    user: root

volumes:
  mongo_data:
