name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: lucas55i
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: lucas55i/flask_api:${{ github.ref_name }}
            